site_name: mbed OS API References

docs_dir: docs

pages:
- ['index.md','Introduction to the mbed OS API References']
- ['APIs/tasks/tasks.md', 'Task management APIs', 'Introduction to task management']
- ['APIs/tasks/rtos.md', 'Task management APIs', 'RTOS']
- ['APIs/tasks/events.md', 'Task management APIs', 'Event loop']
- ['APIs/tasks/Ticker.md', 'Task management APIs', 'Ticker']
- ['APIs/tasks/Time.md', 'Task management APIs', 'Time']
- ['APIs/tasks/TimeOut.md', 'Task management APIs', 'Timeout']
- ['APIs/tasks/Timer.md', 'Task management APIs', 'Timer']
- ['APIs/tasks/wait.md', 'Task management APIs', 'Wait']
- ['APIs/io/inputs_outputs.md', 'Input and output APIs', 'Handling inputs and outputs']
- ['APIs/io/AnalogIn.md', 'Input and output APIs', 'AnalogIn']
- ['APIs/io/AnalogOut.md', 'Input and output APIs', 'AnalogOut']
- ['APIs/io/DigitalIn.md', 'Input and output APIs', 'DigitalIn']
- ['APIs/io/DigitalOut.md', 'Input and output APIs', 'DigitalOut']
- ['APIs/io/DigitalInOut.md', 'Input and output APIs', 'DigitalInOut']
- ['APIs/io/BusIn.md', 'Input and output APIs', 'BusIn']
- ['APIs/io/BusOut.md', 'Input and output APIs', 'BusOut']
- ['APIs/io/BusInOut.md', 'Input and output APIs', 'BusInOut']
- ['APIs/io/PortIn.md', 'Input and output APIs', 'PortIn']
- ['APIs/io/PortOut.md', 'Input and output APIs', 'PortOut']
- ['APIs/io/PortInOut.md', 'Input and output APIs', 'PortInOut']
- ['APIs/io/PwmOut.md', 'Input and output APIs', 'PwmOut']
- ['APIs/io/InterruptIn.md', 'Input and output APIs', 'InterruptIn']
- ['APIs/interfaces/interfaces.md', 'Digital interface APIs', 'Introduction to digital interface']
- ['APIs/interfaces/digital/Serial.md', 'Digital interface APIs', 'Serial']
- ['APIs/interfaces/digital/SPI.md', 'Digital interface APIs', 'SPI']
- ['APIs/interfaces/digital/SPISlave.md', 'Digital interface APIs', 'SPISlave']
- ['APIs/interfaces/digital/I2C.md', 'Digital interface APIs', 'I2C']
- ['APIs/interfaces/digital/I2CSlave.md', 'Digital interface APIs', 'I2CSlave']
- ['APIs/interfaces/digital/CAN.md', 'Digital interface APIs', 'CAN']
- ['APIs/communication/communication_index.md', 'Communication APIs', 'Introduction to communication']
- ['APIs/communication/network_sockets.md', 'Communication APIs', 'Network sockets']
- ['APIs/communication/ethernet.md', 'Communication APIs', 'Ethernet']
- ['APIs/communication/wifi.md', 'Communication APIs', 'WiFi']
- ['APIs/communication/mesh.md', 'Communication APIs', 'Mesh networking']
- ['APIs/communication/ble.md', 'Communication APIs', 'BLE']
- ['APIs/security/security.md', 'Security APIs', 'Securing devices and connections']
- ['APIs/security/uvisor.md', 'Security APIs', 'mbed uVisor']
- ['APIs/security/tls.md', 'Security APIs', 'mbed TLS']
- ['APIs/API_Documentation.md','API documentation', 'How to use the API documentation']
- ['further_reading.md', 'Other sources', 'Further reading and examples']

copyright: © ARM Ltd. Copyright 2016 – ARM mbed IoT Device Platform
