site_name: mbed OS API References

docs_dir: docs

pages:
- ['index.md','Introduction to the mbed OS API References']
- ['APIs/io/inputs_outputs.md', 'Input and output APIs', 'Handling inputs and outputs']
- ['APIs/io/AnalogIn.md', 'Input and output APIs', 'AnalogIn']
- ['APIs/io/AnalogOut.md', 'Input and output APIs', 'AnalogOut']
- ['APIs/io/DigitalIn.md', 'Input and output APIs', 'DigitalIn']
- ['APIs/io/DigitalOut.md', 'Input and output APIs', 'DigitalOut']
- ['APIs/io/DigitalInOut.md', 'Input and output APIs', 'DigitalInOut']
- ['APIs/io/BusIn.md', 'Input and output APIs', 'BusIn']
- ['APIs/io/BusOut.md', 'Input and output APIs', 'BusOut']
- ['APIs/io/BusInOut.md', 'Input and output APIs', 'BusInOut']
- ['APIs/io/PortIn.md', 'Input and output APIs', 'PortIn']
- ['APIs/io/PortOut.md', 'Input and output APIs', 'PortOut']
- ['APIs/io/PortInOut.md', 'Input and output APIs', 'PortInOut']
- ['APIs/io/PwmOut.md', 'Input and output APIs', 'PwmOut']
- ['APIs/io/InterruptIn.md', 'Input and output APIs', 'InterruptIn']
- ['APIs/interfaces/interfaces.md', 'Interface APIs', 'Interface options']
- ['APIs/interfaces/digital/Serial.md', 'Interface APIs', 'Serial']
- ['APIs/interfaces/digital/SPI.md', 'Interface APIs', 'SPI']
- ['APIs/interfaces/digital/SPISlave.md', 'Interface APIs', 'SPISlave']
- ['APIs/interfaces/digital/I2C.md', 'Interface APIs', 'I2C']
- ['APIs/interfaces/digital/I2CSlave.md', 'Interface APIs', 'I2CSlave']
- ['APIs/interfaces/digital/CAN.md', 'Interface APIs', 'CAN']
- ['APIs/interfaces/USBDevice/USBMouse.md', 'Interface APIs', 'USBMouse']
- ['APIs/interfaces/USBDevice/USBKeyboard.md', 'Interface APIs', 'USBKeyboard']
- ['APIs/interfaces/USBDevice/USBMouseKeyboard.md', 'Interface APIs', 'USBMouseKeyboard']
- ['APIs/interfaces/USBDevice/USBHID.md', 'Interface APIs', 'USBHID']
- ['APIs/interfaces/USBDevice/USBMIDI.md', 'Interface APIs', 'USBMIDI']
- ['APIs/interfaces/USBDevice/USBSerial.md', 'Interface APIs', 'USBSerial']
- ['APIs/interfaces/USBDevice/USBAudio.md', 'Interface APIs', 'USBAudio']
- ['APIs/interfaces/USBDevice/USBMSD.md', 'Interface APIs', 'USBMSD']
- ['APIs/interfaces/USBHost/USBHostMouse.md', 'Interface APIs', 'USBHostMouse']
- ['APIs/interfaces/USBHost/USBHostKeyboard.md', 'Interface APIs', 'USBHostKeyboard']
- ['APIs/interfaces/USBHost/USBHostMSD.md', 'Interface APIs', 'USBHostMSD']
- ['APIs/interfaces/USBHost/USBHostSerial.md', 'Interface APIs', 'USBHostSerial']
- ['APIs/interfaces/USBHost/USBHostHub.md', 'Interface APIs', 'USBHostHub']
- ['APIs/communication/network_sockets.md', 'Communication APIs', 'Network sockets']
- ['APIs/communication/ble.md', 'Communication APIs', 'BLE']
- ['APIs/communication/ethernet.md', 'Communication APIs', 'Ethernet']
- ['APIs/communication/wifi.md', 'Communication APIs', 'WiFi']
- ['APIs/security/security.md', 'Security APIs', 'Securing devices and connections']
- ['APIs/security/uvisor.md', 'Security APIs', 'mbed uVisor']
- ['APIs/security/tls.md', 'Security APIs', 'mbed TLS']
- ['APIs/tasks/Time.md', 'Task management APIs', 'Time']
- ['APIs/tasks/Timer.md', 'Task management APIs', 'Timer']
- ['APIs/tasks/rtos.md', 'Task management APIs', 'RTOS']
- ['APIs/tasks/Ticker.md', 'Task management APIs', 'Ticker']
- ['APIs/tasks/wait.md', 'Task management APIs', 'Wait']
- ['APIs/tasks/TimeOut.md', 'Task management APIs', 'TimeOut']
- ['APIs/API_Documentation.md','API documentation', 'How to use the API documentation']
- ['further_reading.md', 'Other sources', 'Further reading and examples']

copyright: © ARM Ltd. Copyright 2016 – ARM mbed IoT Device Platform
